"""Static lookup tables that relate the patch-5.x rig to the old rig.

These are pure data with no behaviour, so they live apart from the code that
consumes them.  Two separate maps are needed because bone *renaming* and
vertex *weight redirection* are different problems:

``BONE_NAME_MAP``
    New-rig bone name -> old-rig bone name, for bones that survive as bones.
    Only entries whose target exists in the loaded template are applied, so
    the table can stay a superset covering both genders.

``VERTEX_BONE_FALLBACK_MAP``
    New-rig bone name -> old-rig bone name, for bones the old rig *drops*.
    A vertex still weighted to a dropped bone is re-pointed at the nearest
    surviving parent listed here.  A vertex that lands on a bone in neither
    table is a bug in these tables, and the transform raises rather than
    silently welding the vertex to the root.
"""

from __future__ import annotations

__all__ = ["BONE_NAME_MAP", "VERTEX_BONE_FALLBACK_MAP"]

BONE_NAME_MAP = {
        "Sub_R_bone_skin03": "R_Sup",
        "R_eye_upper_skin": "R_eye_upper",
        "R_eye_under_skin": "R_eye_under",
        "Sub_L_bone_skin03": "L_Sup",
        "L_eye_upper_skin": "L_eye_upper",
        "L_eye_under_skin": "L_eye_under",
        "mouth_R_side_skin": "R_Mouth_side",
        "mouth_L_side_skin": "L_Mouth_side",
        "Bip01": "Bip01",
        "Bip01 Pelvis": "Bip01 Pelvis",
        "Bip01 Spine": "Bip01 Spine",
        "Bip01 Spine1": "Bip01 Spine1",
        "Bip01 Neck": "Bip01 Neck",
        "Bip01 Head": "Bip01 Head",
        "Rear_bone": "Rear_bone",
        "Lear_bone": "Lear_bone",
        "Mouth_bone": "Mouth_bone",
        "mouth_down_skin": "Mouth",
        "FX_H01": "FX_H01",
        "Bip01 L Clavicle": "Bip01 L Clavicle",
        "Bip01 L UpperArm": "Bip01 L UpperArm",
        "Bip01 L Forearm": "Bip01 L Forearm",
        "Bip01 L Hand": "Bip01 L Hand",
        "Bip01 L Finger0": "Bip01 L Finger0",
        "Bip01 L Finger01": "Bip01 L Finger01",
        "Bip01 L Finger1": "Bip01 L Finger1",
        "Bip01 L Finger11": "Bip01 L Finger11",
        "Bip01 L Finger3": "Bip01 L Finger2",
        "Bip01 L Finger31": "Bip01 L Finger21",
        "Lhand_bone": "Lhand_bone",
        "Shield_bone": "Shield_bone",
        "L_Sbone": "L_Sbone",
        "L_ShCustom": "L_ShCustom",
        "Bip01 R Clavicle": "Bip01 R Clavicle",
        "Bip01 R UpperArm": "Bip01 R UpperArm",
        "Bip01 R Forearm": "Bip01 R Forearm",
        "Bip01 R Hand": "Bip01 R Hand",
        "Bip01 R Finger01": "Bip01 R Finger0",
        "Bip01 R Finger02": "Bip01 R Finger01",
        "Bip01 R Finger11": "Bip01 R Finger1",
        "Bip01 R Finger12": "Bip01 R Finger11",
        "Bip01 R Finger31": "Bip01 R Finger2",
        "Bip01 R Finger32": "Bip01 R Finger21",
        "Rhand_bone": "Rhand_bone",
        "R_Sbone": "R_Sbone",
        "R_ShCustom": "R_ShCustom",
        "L_Bust": "L_Bust",
        "R_Bust": "R_Bust",
        "Rback_bone": "Rback_bone",
        "FX_Hit": "FX_Hit",
        "Lback_bone": "Lback_bone",
        "Neck_bone": "Neck_bone",
        "Wing_bone": "Wing_bone",
        "Rhip_bone": "Rhip_bone",
        "Lhip_bone": "Lhip_bone",
        "Back_bone": "Back_bone",
        "Bip01 L Thigh": "Bip01 L Thigh",
        "Bip01 L Calf": "Bip01 L Calf",
        "Bip01 L Foot": "Bip01 L Foot",
        "Bip01 L Toe0": "Bip01 L Toe0",
        "FX_LF01": "FX_LF01",
        "Bip01 R Thigh": "Bip01 R Thigh",
        "Bip01 R Calf": "Bip01 R Calf",
        "Bip01 R Foot": "Bip01 R Foot",
        "Bip01 R Toe0": "Bip01 R Toe0",
        "FX_RF01": "FX_RF01",
        "CL_Bone": "CL_Bone",
        "bone_L3_00": "bone_L3_00",
        "bone_L3_01": "bone_L3_01",
        "bone_L3_02": "bone_L3_02",
        "bone_L3_03": "bone_L3_03",
        "bone_L3_04": "bone_L3_04",
        "bone_L3_05": "bone_L3_05",
        "bone_L1_00": "bone_L1_00",
        "bone_L1_01": "bone_L1_01",
        "bone_L1_02": "bone_L1_02",
        "bone_L1_03": "bone_L1_03",
        "bone_L1_04": "bone_L1_04",
        "bone_L1_05": "bone_L1_05",
        "bone_L2_00": "bone_L2_00",
        "bone_L2_01": "bone_L2_01",
        "bone_L2_02": "bone_L2_02",
        "bone_L2_03": "bone_L2_03",
        "bone_L2_04": "bone_L2_04",
        "bone_L2_05": "bone_L2_05",
        "bone_R2_00": "bone_R2_00",
        "bone_R2_01": "bone_R2_01",
        "bone_R2_02": "bone_R2_02",
        "bone_R2_03": "bone_R2_03",
        "bone_R2_04": "bone_R2_04",
        "bone_R2_05": "bone_R2_05",
        "bone_R3_00": "bone_R3_00",
        "bone_R3_01": "bone_R3_01",
        "bone_R3_02": "bone_R3_02",
        "bone_R3_03": "bone_R3_03",
        "bone_R3_04": "bone_R3_04",
        "bone_R3_05": "bone_R3_05",
        "bone_R1_00": "bone_R1_00",
        "bone_R1_01": "bone_R1_01",
        "bone_R1_02": "bone_R1_02",
        "bone_R1_03": "bone_R1_03",
        "bone_R1_04": "bone_R1_04",
        "bone_R1_05": "bone_R1_05",
        "Rwaist_bone": "Rwaist_bone",
        "Lwaist_bone": "Lwaist_bone",
        "Reye_bone": "Reye_bone",
        "Leye_bone": "Leye_bone",
    }

VERTEX_BONE_FALLBACK_MAP = {
        "mouth_down_skin": "Mouth",
        "tongue_skin01": "Bip01 Head",
        "tongue_skin02": "Bip01 Head",
        "tongue_skin03": "Bip01 Head",
        "mouth_up_skin": "Bip01 Head",
        "R_eye_skin": "Bip01 Head",
        "L_eye_skin": "Bip01 Head",
        "mouth_up_skin01": "Bip01 Head",
        "mouth_down_skin01": "Mouth",
        "mouth_down_skin02": "Mouth",
        "mouth_up_skin02": "Bip01 Head",
        "mouth_up_skin03": "Bip01 Head",
        "mouth_down_skin03": "Mouth",
        "Sub_R_bone_skin01": "Bip01 Head",
        "Sub_R_bone_skin02": "R_Sup",
        "Sub_R_bone_skin03": "R_Sup",
        "Sub_R_bone_skin04": "R_Sup",
        "Sub_R_bone_skin05": "R_Sup",
        "Sub_L_bone_skin01": "Bip01 Head",
        "Sub_L_bone_skin02": "R_Sup",
        "Sub_L_bone_skin03": "R_Sup",
        "Sub_L_bone_skin04": "R_Sup",
        "Sub_L_bone_skin05": "R_Sup",
        "L_ball_skin_attch_box": "Bip01 Head",  # not sure
        "R_ball_skin_attch_box": "Bip01 Head",  # not sure
        "Reye_bone": "Bip01 Head",
        "Leye_bone": "Bip01 Head",
        "Bip01 L Finger0": "Bip01 L Finger0",
        "Bip01 L Finger02": "Bip01 L Finger01",
        "Bip01 L Finger1": "Bip01 L Finger1",
        "Bip01 L Finger12": "Bip01 L Finger11",
        "Bip01 L Finger2": "Bip01 L Finger2",
        "Bip01 L Finger22": "Bip01 L Finger21",
        "Bip01 L Finger3": "Bip01 L Finger2",
        "Bip01 L Finger32": "Bip01 L Finger21",
        "Bip01 L Finger4": "Bip01 L Finger2",
        "Bip01 L Finger42": "Bip01 L Finger21",
        "Bip01 R Finger0": "Bip01 R Finger0",
        "Bip01 R Finger02": "Bip01 R Finger01",
        "Bip01 R Finger1": "Bip01 R Finger1",
        "Bip01 R Finger12": "Bip01 R Finger11",
        "Bip01 R Finger2": "Bip01 R Finger2",
        "Bip01 R Finger22": "Bip01 R Finger21",
        "Bip01 R Finger3": "Bip01 R Finger2",
        "Bip01 R Finger32": "Bip01 R Finger21",
        "Bip01 R Finger4": "Bip01 R Finger2",
        "Bip01 R Finger42": "Bip01 R Finger21",
        #
        # not sure about ones below, lets wait for an error
        # "FX_D": "Lwaist_bone",
        # "FX_C": "Lwaist_bone",
        # "FX_A": "Rwaist_bone",
        # "FX_B": "Rwaist_bone",
    }
